version: '3.1'
services:
  server:
    container_name: bill
    build:
      context: ../
      dockerfile: ./bill-backend/Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "3001:3001"
