module.exports = {
  development: {
    type: 'mysql',
    host: '',
    port: 3306,
    username: 'root',
    password: '',
    database: '',
    synchronize: false,
    timezone: '+08:00',
  },
  test: {
    type: 'mysql',
    host: '',
    port: 3306,
    username: 'root',
    password: '',
    database: '',
    synchronize: false,
    timezone: '+08:00',
  },
  production: {
    type: 'mysql',
    host: '',
    port: 3306,
    username: 'root',
    password: '',
    database: '',
    synchronize: false,
    timezone: '+08:00',
  },
};
